version: "3"

services:
  graphdb:
    build: 
      context: ./graphdb-docker/free-edition
      args: 
        edition: free
        version: 9.0.0
    ports:
      - 7200:7200
    volumes: 
      - ./graphdb-docker/data:/opt/graphdb/home/data
      - ./graphdb-docker/logs:/opt/graphdb/home/logs

  database:
    image: neo4j:3.5.13
    environment: 
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    ports:
      - ${NEO4J_BOLT_PORT}:${NEO4J_BOLT_PORT}
      - ${NEO4J_BROWSER_PORT}:${NEO4J_BROWSER_PORT}
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
      - ./neo4j/conf:/conf
      - ./neo4j/ontology:/ontology

  backend:
    build: ./backend
    environment: 
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${NEO4J_USERNAME}
      - DATABASE_PASSWORD=${NEO4J_PASSWORD}
      - NEWSAPI_API_KEY=${NEWSAPI_API_KEY}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    depends_on: 
      - database
  frontend:
    build: ./frontend
    environment: 
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT_DOCKER_IMG}
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
